# Generated by Django 3.2.5 on 2021-12-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
