# Generated by Django 4.0 on 2022-01-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_category_subcategory_productoption_subcategory'),
        ('users', '0002_user_birthday_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_point', models.DecimalField(decimal_places=1, max_digits=5)),
                ('size_information', models.DecimalField(decimal_places=1, max_digits=5)),
                ('color_information', models.DecimalField(decimal_places=1, max_digits=5)),
                ('quantity_information', models.DecimalField(decimal_places=1, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
