# Generated by Django 3.2.5 on 2022-01-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
